name: Teste Regressivos PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Setup Chrome e Chromedriver
        uses: nanasess/setup-chrome@v2

      - name: Configurar Display e Chromedriver
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub --verbose --log-path=/tmp/chromedriver.log &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: Esperar o Chromedriver iniciar
        run: sleep 30

      - name: Verificar se o Chromedriver está em execução
        run: |
          ps -ef | grep chromedriver

      - name: Executar Testes
        run: |
          mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting
