name: Teste Regressivos PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome e Chromedriver
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '126.0.6478.126'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional


      - name: Verificar versões do Chrome e Chromedriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Configurar Display e Chromedriver
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -ac &
          chromedriver --url-base=/wd/hub &

      - name: Esperar o Chromedriver iniciar
        run: sleep 30

      - name: Verificar se o Chromedriver está em execução
        run: |
          ps -ef | grep chromedriver

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting
