name: Teste Regressivos PR

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Instalar Java 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          rm google-chrome-stable_current_amd64.deb

      - name: Instalar ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          MAJOR_VERSION=$(echo $CHROME_VERSION | cut -d. -f1)
          if [ $MAJOR_VERSION -eq 126 ]; then
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_126)
          else
            CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          fi
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Verificar versões do Chrome e Chromedriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Configurar Display e Chromedriver
        run: |
          Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          sleep 5
          chromedriver --url-base=/wd/hub > /dev/null 2>&1 &
          sleep 5

      - name: Verificar se o Chromedriver está em execução
        run: |
          ps -ef | grep chromedriver

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting
