name: Teste Regressivos

on:
  pull_request:
    branches: [ master ]

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Instalar Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome*.deb

      - name: Instalar Chromedriver
        uses: nanasess/setup-chromedriver@v2

      - name: Verificar versões do Chrome e Chromedriver
        run: |
          google-chrome --version
          chromedriver --version

      - name: Configurar Display e Chromedriver
        run: |
          export DISPLAY=:99
          sudo Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
          sleep 3 # Adiciona um pequeno atraso
          chromedriver --url-base=/wd/hub &

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting
